version: '3.1'

services:

  telegrambotjr-db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_user
      POSTGRES_DB: dev_telegrambotjr

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080