spring:
  datasource:
    url: jdbc:postgresql://telegrambotjr-db:5432/telegrambotjr_db?useSSL=false&amp;serverTimezone=UTC
    username: prod_user
    password: prod_user
tg-bot:
  username: tg_JR_my_bot
  token: 123token321
  recountNewArticleFixedRate: 900000
  admins: andreypivovaroff
javarush:
  api:
    path: https://javarush.com/api/1.0/rest